# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '{{PROJECT_NAME}}'
primary_region = '{{PRIMARY_REGION}}'
kill_signal = 'SIGINT'
kill_timeout = 30
swap_size_mb = 512

[env]
  PORT = "8080"

[[mounts]]
  source = 'data'
  destination = '/data'

[experimental]
  auto_rollback = true
  allowed_public_ports = [ ]

[[services]]
  protocol = 'tcp'
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  internal_port = 8080
  processes = ['app']
  script_checks = [ ]

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '300s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/resources/healthcheck'
    protocol = 'http'
    tls_skip_verify = false
    headers = { }

[deploy]
release_command = "./release.sh"
